### PR TITLE
Upgrade pins

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
It's unclear to me what the missing transitivity of dependencies means https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#export-runtime-requirements. Do I need to re-export gf2x as well? Or are these covered because this is not a `build` dependency but `host` dependency?

**Comment by isuruf** [comment]
Same as https://github.com/conda-forge/ntl-feedstock/pull/7/files

**Comment by saraedum** [comment]
Sure. It's also clear to me now how the `run_exports` works.

**Comment by isuruf** [comment]
Note that since `gf2x` is not in conda-forge-pinning, a package using gf2x will simply use the latest package at build time and have the run requirement accordingly.

**Pull request closed without merging**
