### PR TITLE
Update to latest version 11.5.1

### PR DESCRIPTION
**Pull request by saraedum**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender

**Comment by saraedum** [comment]
@isuruf, any ideas here?

```
./MakeDesc
make[1]: ./MakeDesc: Bad CPU type in executable
```

Seems like NTL is building a binary that checks the system for features. When cross-compiling this won't work. I guess I could manually run this on an M1 mac and then copy the result over as a patch.

**Comment by isuruf** [comment]
Cross compiling does not work here. I build it locally on an M1 in the past. We can merge this PR without osx-arm64. If you can build the package locally and upload it to your channel and post the log here, I can copy it over to conda-forge.

**Comment by saraedum** [comment]
> Cross compiling does not work here. I build it locally on an M1 in the past. We can merge this PR without osx-arm64. If you can build the package locally and upload it to your channel and post the log here, I can copy it over to conda-forge.

So, there's more trouble after `MakeDesc` even if we patch that one out somehow?

**Comment by saraedum** [comment]
:tada: @isuruf

**Comment by saraedum** [comment]
@isuruf: do you think we could get this one merged?

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
